### ISSUE TITLE
Badass Lemurian and Flamethrower Lemurian combined?

### ISSUE THREAD

**Issue by Coffe-e** [ArcPh1r3/MonsterVariants#2]
Unsure how this happened, but like the title says a flamethrower and badass lemurian spawned as one, and it spammed missile launcher projectiles at me. Will update as I find shit

**Comment by Coffe-e** [comment]
[LogOutput.log](https://github.com/ArcPh1r3/MonsterVariants/files/5977080/LogOutput.log)
here's the log

**Comment by ArcPh1r3** [comment]
this is an intended feature, as stated in the readme
