### ISSUE TITLE
Error in console with latest update / r2?

### ISSUE THREAD

**Issue by Inzanity99** [ArcPh1r3/MonsterVariants#4]
[Info   :   BepInEx] Loading [MonsterVariants 1.3.4]
[Error  : Unity Log] InvalidOperationException: LoadoutAPI is not loaded. Please use [R2APISubmoduleDependency(nameof(LoadoutAPI)]
Stack trace:
R2API.LoadoutAPI.AddSkill (System.Type t) (at <9e56c0ad50a94360869661ef606f8608>:IL_0010)
MonsterVariants.Modules.Skills.RegisterSkills () (at <cccb75f948ee4411b4ad131f7767069d>:IL_0001)
MonsterVariants.MainPlugin.Awake () (at <cccb75f948ee4411b4ad131f7767069d>:IL_0013)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
RoR2.Console:RegisterLogHandler()

**Comment by ArcPh1r3** [comment]
small mistake on my part- will fix when i've got time
